sudo: true
dist: trusty

addons:
  ssh_known_hosts: aqua.aquatan.studio

services: docker

env:
  - DEPLOY_BRANCH=dev

before_install:
  - openssl aes-256-cbc -K $encrypted_49f5ccf52a09_key -iv $encrypted_49f5ccf52a09_iv -in .travis/aquatan_studio.enc -out /tmp/aquatan_studio -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/aquatan_studio
  - ssh-add /tmp/aquatan_studio

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t plannap-api .
  - docker images
  - docker tag plannap-api studioaquatan/plannap-api:latest
  - bash .travis/test.sh

after_success:
  - /bin/bash .travis/push_image.sh

deploy:
  provider: script
  skip_cleanup: true
  script: /bin/bash .travis/deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH = $DEPLOY_BRANCH

notifications:
  email: false
  slack: jphacks2018:Z000DoNdehKSUBPeaZJUkHRh