version: "3"

services:
  webapp:
    container_name: plannap-api
    image: studioaquatan/plannap-api:latest
    env_file:
      - env_files/api.env
    expose:
      - 8000
    depends_on:
      - db
    networks:
      shared:
        aliases:
          - plannap-api
  db:
    image: studioaquatan/mysql-utf8mb4:latest
    container_name: plannap-db
    env_file:
      - env_files/db.env
    volumes:
      - ./env_files/data:/var/lib/mysql
    networks:
      shared:
        aliases:
          - plannap-db
  nginx:
    image: nginx:latest
    container_name: plannap-nginx
    env_file:
      - env_files/static.env
    volumes:
      - ./env_files/conf:/etc/nginx/conf.d
      - ./src/static:/usr/share/www/html/static
      - ./src/media:/usr/share/www/html/media
    depends_on:
      - webapp
    expose:
      - 80
      - 443
    networks:
      shared:
        aliases:
          - plannap-nginx
networks:
  shared:
    external:
      name: shared