# Generated by Django 2.1.2 on 2018-10-20 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255, verbose_name='都道府県名')),
                ('p_code', models.IntegerField(verbose_name='都道府県コード')),
                ('m_name', models.CharField(max_length=255, verbose_name='市区町村名')),
                ('m_code', models.IntegerField(verbose_name='市区町村コード')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='コース名')),
                ('price', models.IntegerField(default=0, verbose_name='予算')),
                ('duration', models.IntegerField(default=0, verbose_name='かかる時間')),
                ('lat', models.FloatField(verbose_name='緯度')),
                ('lon', models.FloatField(verbose_name='経度')),
                ('note', models.TextField(verbose_name='投稿内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='緯度')),
                ('lon', models.FloatField(verbose_name='経度')),
                ('note', models.TextField(verbose_name='ノート')),
                ('image', models.ImageField(upload_to='', verbose_name='投稿画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='plan.Plan', verbose_name='プラン')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='plan.Plan', verbose_name='プラン'),
        ),
    ]
