# Generated by Django 2.1.2 on 2018-10-20 04:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 10, 20, 4, 54, 44, 41129, tzinfo=utc), verbose_name='投稿日時'),
            preserve_default=False,
        ),
    ]
