# Generated by Django 2.1.2 on 2018-10-20 05:54

from django.db import migrations, models
import plan.models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_comment_fav_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(upload_to=plan.models.get_image_path, verbose_name='投稿画像'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='image',
            field=models.ImageField(upload_to=plan.models.get_image_path, verbose_name='投稿画像'),
        ),
    ]
