# Generated by Django 2.1.2 on 2018-10-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_auto_20181020_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='lon',
        ),
    ]
