# Generated by Django 2.1.2 on 2018-10-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_auto_20181020_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='created_at',
            field=models.DateTimeField(verbose_name='投稿日時'),
        ),
    ]
