# Generated by Django 2.1.2 on 2018-10-23 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_auto_20181020_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='plan.Plan', verbose_name='プラン'),
        ),
    ]
