# Generated by Django 2.1.2 on 2018-10-24 13:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0008_auto_20181023_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='fav',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('p_code', 'm_code')},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ('-created_at', 'name')},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='spot',
            options={'ordering': ('order',)},
        ),
        migrations.AlterUniqueTogether(
            name='fav',
            unique_together={('user', 'plan')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('p_name', 'p_code', 'm_name', 'm_code')},
        ),
    ]
