# Generated by Django 2.1.2 on 2018-10-28 06:24

from django.db import migrations
import imagekit.models.fields
import plan.models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_auto_20181024_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=plan.models.get_image_path),
        ),
    ]
