# Generated by Django 2.1.2 on 2018-11-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0013_location_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='map_url',
            field=models.TextField(null=True, verbose_name='経路URL'),
        ),
        migrations.AddField(
            model_name='spot',
            name='map_url',
            field=models.TextField(null=True, verbose_name='地点URL'),
        ),
    ]
