# Generated by Django 2.1.2 on 2018-11-05 09:00
from urllib import parse
from django.db import migrations


def construct_route_url(plan):
    """モデルのメソッドは呼べないため同様の関数を定義"""
    base_url = "https://www.google.com/maps/dir/"
    coordinates = [str(spot.lat)+','+str(spot.lon) for spot in plan.spots.all()]
    if len(coordinates) < 2:
        return 'https://www.google.com/'
    params = {
        'api': 1,
        'travelmode': 'walking',
        'origin': coordinates.pop(0),
        'destination': coordinates.pop(-1),
    }
    if len(coordinates) > 0:
        params['waypoints'] = '|'.join(coordinates)
    query = parse.urlencode(params)
    return base_url + '?' + query


def construct_search_url(spot):
    """モデルのメソッドは呼べないため同様の関数を定義"""
    base_url = "https://www.google.com/maps/search/"
    params = {
        'api': 1,
        'query': str(spot.lat) + ',' + str(spot.lon)
    }
    query = parse.urlencode(params)
    return base_url + '?' + query


def make_url(apps, schema_editor):
    """
    現在DBに入っているデータから動的にURLを生成して入れる
    """
    Plan = apps.get_model('plan', 'Plan')
    for plan in Plan.objects.all():
        plan.map_url = construct_route_url(plan)
        plan.save()
    Spot = apps.get_model('plan', 'Spot')
    for spot in Spot.objects.all():
        spot.map_url = construct_search_url(spot)
        spot.save()


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0014_auto_20181105_1759'),
    ]

    operations = [
        migrations.RunPython(make_url)
    ]
