# Generated by Django 2.1.2 on 2018-10-28 06:54

import accounts.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181020_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='icons/user.png', null=True, upload_to=accounts.models.get_image_path, verbose_name='アイコン'),
        ),
    ]
